### PR TITLE
add new dates

### PR DESCRIPTION
**Pull request by favergara**
I have added new dates 

Fecha de Vencimiento: 2017-04-04 19:14:09
Expires: 03 Apr 2017

### CODE REVIEW

**Comment by glensc** [comment]
domain to test required

**Comment by favergara** [comment]
venevision.com.ve  = Fecha de Vencimiento: 2017-04-04 19:14:09
paginaswebecuador.ec = Expires: 03 Apr 2017

**Comment by favergara** [comment]
I have problems with this string:
valemas.cl
Fecha de expiración (Expiration date): 2017-05-03 12:46:02 CLT

**Comment by favergara** [comment]
I already fixed the problem with "Fecha de expiración (Expiration date): 2017-05-03 12:46:02 CLT" format.

**Comment by IvMaks** [comment]
check_domain.sh  -d 1003.ruCRITICAL - Domain 1003.ru expired 1342 days ago (2013-07-02). | domain_days_until_expiry=-1342;30;7

**Comment by glensc** [comment]
looks like you created your PR from master branch adding commits you did not intend to. re-create the PR with only neccessary commits.

**Pull request closed without merging**
