### PR TITLE
Drop utils.sh

### PR DESCRIPTION
**Pull request by jeanpaulgalea**
Related to #66. Check commit message for more details.

### CODE REVIEW

**Comment by glensc** [comment]
your PR contains unrelated changes. rebase against `master` and `git push -f`

**Comment by jeanpaulgalea** [comment]
Shouldn't you be able to merge? The unrelated changes are from #67, so merging this to master should apply cleanly now.

**Comment by glensc** [comment]
seems github broken and showing two commits here. it has even same commit id as one in master

**Comment by jeanpaulgalea** [comment]
Cheers!

**Pull request merged**
